[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/sheet-api"
  to = "/.netlify/functions/sheet-api"
  status = 200

[[redirects]]
  from = "/api/admin-auth"
  to = "/.netlify/functions/admin-auth"
  status = 200

[[redirects]]
  from = "/api/sheet-csv"
  to = "/.netlify/functions/sheet-csv"
  status = 200

[[redirects]]
  from = "/api/sheet-submissions-csv"
  to = "/.netlify/functions/sheet-submissions-csv"
  status = 200

[[redirects]]
  from = "/api/trigger-sync"
  to = "/.netlify/functions/trigger-sync"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
