/** Thursday 90-day extras for the all-search workflow mockup. Not wired to cron. */

import type { MockCandidate, MockProvider } from './experimentAdminWorkflowMockupData'

export const THURSDAY_WINDOW_TODAY = 'This Sat–Sun and next Sat–Sun only (Sep 19–20 & Sep 26–27)'
export const THURSDAY_WINDOW_PROPOSED = 'Next ~90 days (Sep 14 – Dec 13, 2026)'

export const THURSDAY_EXTRA_CANDIDATES: MockCandidate[] = [
  {
    id: 'cand-little-gym',
    title: 'Parent/Tot class',
    dateLabel: 'Mon & Wed options · through Dec',
    dateSort: '2026-09-15',
    city: 'Mountain View',
    venue: 'The Little Gym',
    type: 'Social & Play',
    source: 'Watchlist',
    officialUrl: 'https://www.thelittlegym.com/',
    sourceType: 'Official studio page',
    lastChecked: 'Sep 14',
    ageGuidance: '',
    cost: 'Paid',
    registration: 'Registration required',
    goodToKnow: '',
    note: 'New vendor. Confirm ages 0–5 vs 3–6, then one series row. Year-round — Browse, not a seasonal collection.',
    flags: ['age-unclear', 'official-source'],
    missing: 'Official age range',
  },
  {
    id: 'cand-foam',
    title: 'Village foam play morning',
    dateLabel: 'Sat, Sep 26 · 10:00 AM',
    dateSort: '2026-09-26',
    city: 'Mountain View',
    venue: 'Village at San Antonio Center',
    type: 'Social & Play',
    source: 'Weekend search',
    officialUrl: 'https://villageatsanantoniocenter.com/events/',
    sourceType: 'Official events page',
    lastChecked: 'Sep 14',
    ageGuidance: 'Little ones welcome',
    cost: 'Free',
    registration: 'Drop-in',
    goodToKnow: 'Outdoor play morning. Check the center page if rain is in the forecast.',
    note: 'Core-city pop-up inside the 90-day window. Add to Browse. Seasonal only if you also check a collection.',
    flags: ['official-source'],
  },
  {
    id: 'cand-filoli-inbox',
    title: 'Filoli Harvest Days',
    dateLabel: 'Sat–Sun, Oct 10–11 · 10:00 AM',
    dateSort: '2026-10-10',
    city: 'Woodside',
    venue: 'Filoli Historic House & Garden',
    type: 'Outdoor',
    source: 'Regional',
    officialUrl: 'https://filoli.org/',
    sourceType: 'Official calendar',
    lastChecked: 'Sep 14',
    ageGuidance: '',
    cost: 'Paid',
    registration: 'Tickets',
    goodToKnow: 'Garden harvest weekend on the official calendar.',
    note: 'Out of area. Already sitting in Events → Unplaced. Do not add a second record.',
    flags: ['official-source'],
    match: {
      title: 'Filoli Harvest Days',
      status: 'Draft',
      placement: 'Unplaced · not public',
    },
  },
]

export const THURSDAY_EXTRA_PROVIDERS: MockProvider[] = [
  {
    id: 'prov-fit4mom',
    name: 'FIT4MOM Silicon Valley Central',
    city: 'Mountain View',
    url: 'https://fit4momsiliconvalleycentral.com/',
    programming: 'Stroller Strides · Parent & Me',
    lastChecked: 'Sep 8',
    why: 'Already on Calendar Watchlist. Recheck the weekly graphic.',
  },
  {
    id: 'prov-talo',
    name: 'Talo Yoga',
    city: 'Mountain View',
    url: 'https://www.taloyoga.com/',
    programming: 'Baby & Me · CircleMoms',
    lastChecked: 'Sep 10',
    why: 'Semester cohorts, not drop-in. One series row.',
  },
  {
    id: 'prov-music-together',
    name: 'Music Together',
    city: 'Palo Alto',
    url: 'https://www.musictogether.com/',
    programming: 'Parent & Me music',
    lastChecked: 'Sep 10',
    why: 'Fall semester already live. Recheck when the next term posts.',
  },
]

export type CoverageKind = 'library' | 'venue' | 'provider' | 'channel'
export type CoverageMark = 'looked' | 'todo' | 'blocked'

export type CoverageItem = {
  id: string
  kind: CoverageKind
  name: string
  city: string
  note: string
  defaultMark: CoverageMark
}

export const THURSDAY_COVERAGE: CoverageItem[] = [
  {
    id: 'lib-palo-alto',
    kind: 'library',
    name: 'Palo Alto Library (BiblioCommons)',
    city: 'Palo Alto',
    note: 'Sunday scrape covers storytimes & classes. Thursday only checks for one-offs the scrape missed.',
    defaultMark: 'looked',
  },
  {
    id: 'lib-los-altos',
    kind: 'library',
    name: 'Los Altos + Woodland (SCCL)',
    city: 'Los Altos',
    note: 'Sunday scrape. Thursday skips weekly storytimes already queued.',
    defaultMark: 'looked',
  },
  {
    id: 'lib-mv',
    kind: 'library',
    name: 'Mountain View Library (LibCal)',
    city: 'Mountain View',
    note: 'Sunday scrape. City special events are a separate calendar.',
    defaultMark: 'looked',
  },
  {
    id: 'lib-sunnyvale',
    kind: 'library',
    name: 'Sunnyvale Public Library · Kids',
    city: 'Sunnyvale',
    note: 'Site blocks scrapers. Manual check on the kids calendar.',
    defaultMark: 'blocked',
  },
  {
    id: 'lib-linden',
    kind: 'library',
    name: 'Linden Tree Books',
    city: 'Los Altos',
    note: 'Also on the Sunday scrape. Recheck storytimes / author events.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-pa-directory',
    kind: 'venue',
    name: 'Palo Alto Events Directory',
    city: 'Palo Alto',
    note: 'Official city calendar — first stop for festivals and rec programs.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-gamble',
    kind: 'venue',
    name: 'Elizabeth F. Gamble Garden',
    city: 'Palo Alto',
    note: 'Kids / family calendar. Pumpkin decorating is in this week’s inbox.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-village',
    kind: 'venue',
    name: 'Village at San Antonio Center',
    city: 'Mountain View',
    note: 'Shopping-center play days. Foam morning is in this week’s inbox.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-magical-bridge',
    kind: 'venue',
    name: 'Magical Bridge Palo Alto',
    city: 'Palo Alto',
    note: 'Playground programs and community days. Official calendar: magicalbridge.org/paloaltoevents.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-magical-bridge-mv',
    kind: 'venue',
    name: 'Magical Bridge · Mountain View (Rengstorff)',
    city: 'Mountain View',
    note: 'Performance Series is 4:00–5:00 PM Sep 5, 19, 24 & Oct 1, 9, 15 — not Wed 9/16, 9/30, 10/14. One series row in this week’s inbox.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-mv-special',
    kind: 'venue',
    name: 'Mountain View Special Events',
    city: 'Mountain View',
    note: 'City festivals (Harvest History). Akamai often blocks automated fetch.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-sunnyvale-special',
    kind: 'venue',
    name: 'Sunnyvale Special Events + Downtown',
    city: 'Sunnyvale',
    note: 'Mid-Autumn, Hands on the Arts, Cityline. Skip food-only fests.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-dla',
    kind: 'venue',
    name: 'Downtown Los Altos',
    city: 'Los Altos',
    note: 'Family Fun Days and downtown events calendar.',
    defaultMark: 'todo',
  },
  {
    id: 'ven-google',
    kind: 'venue',
    name: 'Google Visitor Experience · Gradient Canopy',
    city: 'Mountain View',
    note: 'Huddle / plaza pop-ups. Watchlist cadence is monthly, not every Thursday.',
    defaultMark: 'looked',
  },
  {
    id: 'ven-pa-rec',
    kind: 'venue',
    name: 'Palo Alto Recreation · kids & family',
    city: 'Palo Alto',
    note: 'City rec classes and community events beyond the Events Directory.',
    defaultMark: 'todo',
  },
  {
    id: 'ven-la-rec',
    kind: 'venue',
    name: 'Los Altos Recreation',
    city: 'Los Altos',
    note: 'Parent & Tot and seasonal rec programs.',
    defaultMark: 'todo',
  },
  {
    id: 'ven-jcc',
    kind: 'venue',
    name: 'Oshman Family JCC · Jeff Center',
    city: 'Palo Alto',
    note: 'Family play and holiday programs.',
    defaultMark: 'todo',
  },
  {
    id: 'prov-fit4mom-cov',
    kind: 'provider',
    name: 'FIT4MOM Silicon Valley Central',
    city: 'Palo Alto / MV',
    note: 'Watchlist. Recheck the weekly graphic on Mondays.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-talo-cov',
    kind: 'provider',
    name: 'Talo Yoga',
    city: 'Mountain View',
    note: 'Baby & Me series is in the inbox. One row, not weekly spam.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-marti',
    kind: 'provider',
    name: 'Marti Foster Yoga',
    city: 'Mountain View',
    note: 'Parent + baby outdoor yoga. Confirm current series dates.',
    defaultMark: 'todo',
  },
  {
    id: 'prov-mini-yoga-cov',
    kind: 'provider',
    name: 'Mini Yoga Club',
    city: 'Sunnyvale / Palo Alto',
    note: 'Already on Calendar Watchlist.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-mt-cov',
    kind: 'provider',
    name: 'Music Together',
    city: 'Palo Alto / MV',
    note: 'Fall semester already live. Recheck when the next term posts.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-little-gym-cov',
    kind: 'provider',
    name: 'The Little Gym of Mountain View',
    city: 'Mountain View',
    note: 'Not on Watchlist yet. Parent/Tot is in this week’s inbox — confirm 0–5 vs 3–6.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-bunnyhive-cov',
    kind: 'provider',
    name: 'Bunnyhive',
    city: 'Sunnyvale',
    note: 'Fall calendar not posted. Inbox Watch.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-ipa',
    kind: 'provider',
    name: 'IPA USA California',
    city: 'Palo Alto',
    note: 'Pop-up playdays. Instagram often posts first; confirm on ipausaca.org.',
    defaultMark: 'looked',
  },
  {
    id: 'prov-sunnyvale-rec',
    kind: 'provider',
    name: 'Sunnyvale Recreation · Parent & Tot',
    city: 'Sunnyvale',
    note: 'Super Safari and preschool Parent & Tot. One semester row, not weekly spam.',
    defaultMark: 'looked',
  },
  {
    id: 'ch-web',
    kind: 'channel',
    name: 'Open web search',
    city: 'Core four + Worth a little drive',
    note: 'Same hunt Thursday morning for core four and ~1 hour. Official calendars first, then “toddler / ages 0–5” + city + date window.',
    defaultMark: 'looked',
  },
  {
    id: 'ch-kidfun',
    kind: 'channel',
    name: 'Bay Area Kid Fun',
    city: 'Core four + Worth a little drive',
    note: 'Leads only. Open the official page before writing copy. Core-city finds → Browse; out of area → Worth a little drive.',
    defaultMark: 'looked',
  },
  {
    id: 'ch-funcheap',
    kind: 'channel',
    name: 'Funcheap SF',
    city: 'Core four + Worth a little drive',
    note: 'City + kids filters. Same rule: official URL required.',
    defaultMark: 'todo',
  },
  {
    id: 'ch-ig',
    kind: 'channel',
    name: 'Instagram',
    city: 'Core four + Worth a little drive',
    note: 'ca.ipa.usa, city rec, libraries, Gamble, Linden Tree, Magical Bridge (PA + MV). Post is OK only if it is the announcement.',
    defaultMark: 'looked',
  },
  {
    id: 'ch-fb',
    kind: 'channel',
    name: 'Facebook',
    city: 'Core four + Worth a little drive',
    note: 'Pointer to an official URL, not a screenshot-only source.',
    defaultMark: 'todo',
  },
  {
    id: 'ch-xhs',
    kind: 'channel',
    name: '小紅書',
    city: 'Core four + Worth a little drive',
    note: 'Hunt both local pop-ups and ~1 hour farms/festivals. Never use a 小紅書 URL as the event link unless that post is the announcement — official page still required. Do not scrape.',
    defaultMark: 'todo',
  },
  {
    id: 'ch-share',
    kind: 'channel',
    name: 'Puddles Share form',
    city: 'Parent submissions',
    note: 'Saturday craft morning is in the inbox — confirm on the city page.',
    defaultMark: 'looked',
  },
  {
    id: 'ch-eventbrite',
    kind: 'channel',
    name: 'Eventbrite · kids / family',
    city: 'Core four + Worth a little drive',
    note: 'Leads only. Prefer the host’s own page over the Eventbrite listing when both exist.',
    defaultMark: 'todo',
  },
  {
    id: 'ch-nextdoor',
    kind: 'channel',
    name: 'Nextdoor',
    city: 'Core four + Worth a little drive',
    note: 'Neighborhood pop-up leads. Still need an official URL before Add.',
    defaultMark: 'todo',
  },
]

export const COVERAGE_GROUPS: { kind: CoverageKind; title: string; lede: string }[] = [
  {
    kind: 'library',
    title: 'Libraries',
    lede: 'Sunday scrape already covers PA / Los Altos / MV. Thursday is for gaps and Sunnyvale (manual).',
  },
  {
    kind: 'venue',
    title: 'Venues & city calendars',
    lede: 'Places little ones actually go: gardens, play days, city festivals, downtown calendars.',
  },
  {
    kind: 'provider',
    title: 'Local providers',
    lede: 'Parent & Me studios and class series. One row per semester, not weekly spam.',
  },
  {
    kind: 'channel',
    title: 'Search channels',
    lede: 'Same list Thursday morning for core four and ~1 hour. Split geography when you Add — not when you search. Roundups and social are pointers; official page still required.',
  },
]
